// Temporary illustrative product images generated with OpenAI's built-in image generator.
// Keep this registry limited to files that physically exist in public/images/products/generated/.
export const generatedProductImages = {
  "alfajor": "images/products/generated/alfajor-x1.png",
  "alfajor-grande": "images/products/generated/alfajor-grande.png",
  "alfajor-x1": "images/products/generated/alfajor-x1.png",
  "alfajores-x12": "images/products/generated/alfajores-x12.png",
  "anisete": "images/products/generated/anisete.png",
  "arrollado-con-dulce-de-leche": "images/products/generated/arrollado-con-dulce-de-leche.png",
  "bandeja-lactea-surtida": "images/products/generated/bandeja-lactea-surtida.png",
  "bandeja-neutra": "images/products/generated/bandeja-neutra.png",
  "bizcochitos-y-cuernitos": "images/products/generated/bizcochitos-y-cuernitos.png",
  "boios-de-berenjena": "images/products/generated/boios-de-berenjena.png",
  "boios-de-verdura": "images/products/generated/boios-de-verdura.png",
  "bombas-x12": "images/products/generated/bombas-x12.png",
  "bombas": "images/products/generated/bombas-x12.png",
  "bombas-x20": "images/products/generated/bombas-x20.png",
  "brownie-x12": "images/products/generated/brownie-x12.png",
  "budines": "images/products/generated/budines.png",
  "canelones-lacteos": "images/products/generated/canelones-lacteos.png",
  "canon-grande": "images/products/generated/canon-grande.png",
  "canoncitos-de-copetin-x12": "images/products/generated/canoncitos-de-copetin-x12.png",
  "cocadas": "images/products/generated/cocadas.png",
  "conito-x1": "images/products/generated/conito-x1.png",
  "conito": "images/products/generated/conito-x1.png",
  "conitos-x12": "images/products/generated/conitos-x12.png",
  "coquitos": "images/products/generated/coquitos.png",
  "dulces-arabes-x12": "images/products/generated/dulces-arabes-x12.png",
  "empanada-de-carne": "images/products/generated/empanada-de-carne.png",
  "empanada-de-carne-frita": "images/products/generated/empanada-de-carne-frita.png",
  "empanada-de-cebolla": "images/products/generated/empanada-de-cebolla.png",
  "empanada-de-choclo": "images/products/generated/empanada-de-choclo.png",
  "empanada-de-pollo": "images/products/generated/empanada-de-pollo.png",
  "ensalada-de-lechuga-tomate-zanahoria-y-huevo": "images/products/generated/ensalada-de-lechuga-tomate-zanahoria-y-huevo.png",
  "ensalada-de-palta-tomate-y-huevo": "images/products/generated/ensalada-de-palta-tomate-y-huevo.png",
  "ensalada-de-remolacha-papa-y-huevo": "images/products/generated/ensalada-de-remolacha-papa-y-huevo.png",
  "ensalada-rusa": "images/products/generated/ensalada-rusa.png",
  "filete-con-pure": "images/products/generated/filete-con-pure.png",
  "grisines": "images/products/generated/grisines.png",
  "kakes-1-2": "images/products/generated/kakes-1-2.png",
  "kakes-1-4": "images/products/generated/kakes-1-4.png",
  "kipes": "images/products/generated/kipes.png",
  "knishes-de-papa": "images/products/generated/knishes-de-papa.png",
  "lajmayin-abierta": "images/products/generated/lajmayin-abierta.png",
  "lajmayin-cerrada": "images/products/generated/lajmayin-cerrada.png",
  "lentejas-con-arroz": "images/products/generated/lentejas-con-arroz.png",
  "maicena-x1": "images/products/generated/maicena-x1.png",
  "maicena": "images/products/generated/maicena-x1.png",
  "maicena-x12": "images/products/generated/maicena-x12.png",
  "masas-finas-x12": "images/products/generated/masas-finas-x12.png",
  "masas-secas": "images/products/generated/masas-secas.png",
  "merenguecitos": "images/products/generated/merenguecitos.png",
  "merengues-con-dulce-de-leche-x12": "images/products/generated/merengues-con-dulce-de-leche-x12.png",
  "mosaico": "images/products/generated/mosaico.png",
  "palmeras": "images/products/generated/palmeras.png",
  "pepas": "images/products/generated/pepas.png",
  "pollo-con-papas": "images/products/generated/pollo-con-papas.png",
  "porotos-con-arroz": "images/products/generated/porotos-con-arroz.png",
  "salpicon-de-pollo": "images/products/generated/salpicon-de-pollo.png",
  "sambusak": "images/products/generated/sambusak.png",
  "sandwich-de-milanesa": "images/products/generated/sandwich-de-milanesa.png",
  "sandwich-de-suprema": "images/products/generated/sandwich-de-suprema.png",
  "scons": "images/products/generated/scons.png",
  "sfanjat-de-verdura": "images/products/generated/sfanjat-de-verdura.png",
  "souffle-lacteo": "images/products/generated/souffle-lacteo.png",
  "tortilla-de-papa": "images/products/generated/tortilla-de-papa.png",
  "vainillas": "images/products/generated/vainillas.png",
};

export const generatedProductImageMetadata = {
  source: "OpenAI built-in image generator",
  illustrative: true,
  temporary: true,
};
